name: streamlit-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - streamlit==1.32.0
    - snowflake-snowpark-python==1.31.1
    - snowflake-connector-python==3.3.1
    - pandas==2.0.0
    - python-dotenv==1.0.0
    - requests==2.31.0
